js/main.js, main.html, style/main.css, style/style.css
메인 화면 배너 기초 작업 + js fetch로 데이터 불러오기
=> feat:main banner style

login.html, style/login.css, style/style.css
=> feat:login style

js/main.js, style/reset.css, style/style.css
- reset.css를 추가하였습니다.
- 기존에 브라우저가 주던 스타일을 초기화하는 스타일이라서 조금 스타일이 변경될 수 있습니다.
=> style: add reset css

detail.html, detail.js, style/detail.css
API 연결 및 메뉴 underline 추가
(underline 오류 수정 전)
=> feat connect API

detail.html, js/detail.js, style/detail.css
=> feat:detail page add

js/detail.js, js/main.js, main.html, style/main.css, style/style.css
- dev에  있는 내용을 pull해서 충돌을 수정했습니다. (혹시 dev쪽에 있는 내용으로 수정해서 문제는 없을 것 같은데 문제가 생기면 말씀해주세요)
- 메인 페이지에 배너에 애니메이션을 추가하였습니다.
- 서치 기능을 fetch와 연결하여 데이터를 가지고 올 수 있습니다. (차후에 페이지에 랜더링 할 수 있도록 기능 구현 하겠습니다.)
- 클릭한 id를 받아서 detail.html 페이지에 이동이 가능하도록 하였습니다.
=> feat: merge and search is connected with fetch url

detail.html, js/detail.js, js/login.js, login.html, style/detail.css, style/login.css
=> login js add

detail.html, js/detail.js, js/login.js, style/detail.css, style/login.css
=> feat:detail page style

js/detail.js, js/main.js, style/style.css
=> fix: error fix

detail.html, js/detail.js, style/detail.css
=> feat screenshot src

js/main.js, main.html
=> fix: error fix while merging 

js/main.js
=> fix: error fix delete duplicate code

js/detail.js, js/main.js, main.html
- rating 기준 캐러셀이 노출되지 않는 문제를 수정하였습니다.
- detail.js에 이미지들을 캐러셀에 노출되도록 수정하였습니다.
=> fix: error fix in main.js and detail.js

index.html
=> fix: index contents text fixed

js/login.js, main.html, style/detail.css
- 디테일 페이지 merge 중 코드가 이상한 부분을 수정하였습니다.
=> fix: merging error in detail page

detail.html
- yongmin 브랜치 내용을 dev 로 merge하겠습니다.
=> merge: yongmin to dev

js/index.js, js/main.js, main.html, style/detail.css, style/index.css, style/style.css, style/variable.css
=> fix: main.html error fix

detail.html, index.html, js/main.js, main.html
=> fix: change nav-bar

detail.html, index.html, main.html, style/index.css, style/style.css
로그아웃을 누르면 로그인 페이지로 이동하게 만들어놨습니다.
=> logout function

js/main.js, style/detail.css, style/style.css
detail page에 css 내용을 수정하였습니다.
- 네브바 로고 적용 안 되는 css
- 배경색 흰 색인 css
=> detail page css fix
